### ISSUE TITLE
Erro ao inicializar o projeto

### ISSUE THREAD

**Issue by bruno3du** [edilsonmadsen/dropboxCloneJS#1]
Estava tentando inicializar seu projeto para poder analisar, mas fiquei bloqueado pelo seguinte problema.

![Captura de tela de 2023-02-01 21-03-42](https://user-images.githubusercontent.com/83365446/216196588-3de2333f-ebad-4085-a568-735cb38f5507.png)

Quando executo o npm start indicado pelo seu README e que é oferecido pelo package.json ele executa o "./bin/www" só que o mesmo foi ignorado pelo github e sendo assim não tenho como executa como. Veja o abaixo o /bin ignorado:

![Captura de tela de 2023-02-01 21-01-34](https://user-images.githubusercontent.com/83365446/216196866-2f91b8bd-488b-4bd0-95db-4a7ad6117600.png)

Para que eu ou qualquer outra pessoa possa acessar seu projeto e executa-lo, descomente o /bin e suba uma nova versão do seu projeto.

**Comment by edilsonmadsen** [comment]
alteração feita, adicionado o bin e feito o commit para o repositório
